### ISSUE TITLE
Pororo-SV dataset

### ISSUE THREAD

**Issue by LSJ1994** [yitong91/StoryGAN#10]
Hello author.

I am really interested in your storyGAN. 
I want to use your Pororo-SV dataset. Can i get a Pororo-SV dataset.?

**Comment by yitong91** [comment]
Can you send me an email? Thanks

**Comment by LSJ1994** [comment]
I couldn't find your email address...

My email address is zaxscv@korea.ac.kr.

Could you please send me a email? Thank you.

**Comment by epejhan90** [comment]
Hi, I'm interested in your article and implementing it. I need your Pororo-SV dataset, would you please send it for me?
My email : elham.pezhhan90@gmail.com

Thanks.

**Comment by Hardik-hi** [comment]
@LSJ1994 @epejhan90 Did you get the dataset, if yes can you please add it to this repo via a PR?
