### ISSUE TITLE
Whether the Pororo-SV dataset can be published

### ISSUE THREAD

**Issue by Gyann-z** [yitong91/StoryGAN#4]
Dear authors, I am very interested in your work. I want to reproduce your work on the Pororo-SV dataset. Can you publish the download address of this dataset? I would appreciate it very much. Looking forward to your reply.

**Comment by yitong91** [comment]
Hi, Pororo dataset is published at https://github.com/Kyung-Min/PororoQA .

**Comment by Gyann-z** [comment]
Thank you for your reply. Actually what I want is your modified Pororo-SV dataset. I have troubles in how the frame image sampled from the video clip matches the sentence. If you could provide the dataset, that would help me a lot.

**Comment by yitong91** [comment]
The dataset is too large to distribute. But I can give you the python code to do that. Can you send me an email?

**Comment by zgy1997** [comment]
Thank you so much！！ 771019062@qq.com

**Comment by Crownwzt** [comment]
Dear author i also want the original code the reproduced your work on the Pororo-SV dataset.  Can you share them with me? My emali address is 945530858@qq.com

**Comment by AymanTalkhani** [comment]
Hey @yitong91. I have recently come across your work and am really interested in applying it to my own research on GANs. I would love to have an opportunity to try out the code on your modified Pororo-SV dataset. I have tried looking for your contact email but have been unable to find it on the published paper. Please share the python code with me on the following email if possible: (aat2193@columbia.edu). I would really appreciate it.

**Comment by Hardik-hi** [comment]
@Gyann-z Did you get the code, if yes can you please add it to this repo via a PR?

**Comment by Crownwzt** [comment]
您的邮件我已收到，请您放心，我会尽快给您回复。

**Comment by nandini11509** [comment]
> Thank you for your reply. Actually what I want is your modified Pororo-SV dataset. I have troubles in how the frame image sampled from the video clip matches the sentence. If you could provide the dataset, that would help me a lot.

@Gyann-z @Hardik-hi 
Hey, can you provide the same to me?
my email is nandini11509@gmail.com
It would be of great help.
Thankyou.

**Comment by Crownwzt** [comment]
您的邮件我已收到，请您放心，我会尽快给您回复。
